# Generated by Django 5.1.3 on 2024-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_myuser_email_verified_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
