# Generated by Django 5.1.3 on 2024-11-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default=' ', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=400, unique=True, verbose_name='URL изображения'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='goods.categories', verbose_name='Категория'),
        ),
    ]
