# Generated by Django 5.1.3 on 2024-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_products_category_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, default='Y', max_length=1, verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
