# Generated by Django 5.1.3 on 2025-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_products_image_alter_products_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(blank=True, max_length=25, verbose_name='Тип'),
        ),
    ]
