# Generated by Django 5.1.3 on 2025-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.TextField(blank=True, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_index',
            field=models.CharField(default='', max_length=20, verbose_name='Почтовый индекс'),
        ),
    ]
