# Generated by Django 5.1.3 on 2025-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя заказчика'),
        ),
    ]
